version: '2'
services:
  mongodb:
    image: scottford/np-mongodb
    command: --strategy at-once
  national-parks:
    image: scottford/national-parks
    ports:
      - 8081:8080
      - 9631:9631
    links:
      - mongodb
    depends_on:
      - mongodb
    command: --strategy at-once --channel stable --peer mongodb --bind database:np-mongodb.default
